# Generated by Django 6.0.6 on 2026-06-22 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('stores', '0003_rename_deleted_store_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.IntegerField()),
                ('interest_rate', models.IntegerField(default=0)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('partial', 'Partiellement remboursé'), ('paid', 'Remboursé'), ('overdue', 'En retard')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='customers.customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('cash', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('Om', 'Orange money')], default='cash', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='credits.credit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
