# Generated by Django 6.0.6 on 2026-06-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_creditpayment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpayment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
