# Generated by Django 6.0.6 on 2026-06-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('vir', 'Virement'), ('cheque', 'Chèque'), ('om', 'Orange Money')], max_length=20),
        ),
    ]
