# Generated by Django 6.0.6 on 2026-07-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Espèces'), ('vir', 'Virement'), ('cheque', 'Chèque'), ('om', 'Orange Money')], default='cash', max_length=20),
        ),
    ]
