# Generated by Django 6.0.6 on 2026-06-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('partial', 'Partiel'), ('paid', 'Payé')], default='unpaid', max_length=20),
        ),
    ]
