# Generated by Django 6.0.6 on 2026-06-24 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='total_amount',
            new_name='total',
        ),
    ]
