# Generated by Django 6.0.6 on 2026-06-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_rename_total_amount_purchase_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='invoice_number',
            new_name='reference',
        ),
    ]
