# Generated by Django 6.0.6 on 2026-08-06 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_rename_invoice_number_purchase_reference'),
        ('subscriptions', '0002_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='subscriptions.company'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='subscriptions.company'),
        ),
    ]
