# Generated by Django 6.0.6 on 2026-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('owner', 'Propriétaire'), ('manager', 'Gérant'), ('cashier', 'Caissier'), ('seller', 'Vendeur')], default='seller', max_length=20),
        ),
    ]
