# Generated by Django 6.0.6 on 2026-06-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='apply_vat',
            field=models.BooleanField(default=False, verbose_name='Appliquer TVA (18%)'),
        ),
    ]
