# Generated by Django 6.0.6 on 2026-06-20 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_apply_vat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='apply_vat',
        ),
    ]
