# Generated by Django 6.0.6 on 2026-06-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_remove_document_apply_vat'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quotes.quote'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('purchase_order', 'Bon achat'), ('delivery_note', 'Bon livraison'), ('invoice', 'Facture'), ('quote', 'Devis')], max_length=30),
        ),
    ]
