# Generated by Django 6.0.6 on 2026-06-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_quote_alter_document_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='quote',
        ),
    ]
