# Generated by Django 6.0.6 on 2026-06-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_document_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('purchase_order', 'Bon achat'), ('delivery_note', 'Bon livraison'), ('invoice', 'Facture')], max_length=30),
        ),
    ]
