# Generated by Django 6.0.6 on 2026-08-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_address_company_bank_account_company_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='period_month',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
