# Generated by Django 6.0.6 on 2026-08-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_period_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='period_month',
        ),
        migrations.AlterField(
            model_name='payment',
            name='period_month',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
