# Generated by Django 6.0.6 on 2026-06-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
