# Generated by Django 6.0.6 on 2026-06-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='deleted',
            new_name='is_deleted',
        ),
    ]
