# Generated by Django 6.0.6 on 2026-08-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_slug_alter_marque_name_and_more'),
        ('stocks', '0002_stock_company'),
        ('stores', '0004_store_company'),
        ('subscriptions', '0002_company_logo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('company', 'store', 'product'), name='unique_stock_per_company_store_product'),
        ),
    ]
