# Generated by Django 6.0.6 on 2026-06-21 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='quotes/'),
        ),
    ]
