# Generated by Django 6.0.6 on 2026-06-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='apply_vat',
        ),
    ]
