# Generated by Django 6.0.6 on 2026-06-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_remove_quote_apply_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='reduction',
            field=models.IntegerField(default=10),
        ),
    ]
