# Generated by Django 6.0.6 on 2026-07-05 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_delivery_fee_quote_reduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='reduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='vat_rate',
            field=models.IntegerField(default=0),
        ),
    ]
