# Generated by Django 6.0.6 on 2026-07-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_quote_reduction_alter_quote_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('invoiced', 'Facturé')], default='draft', max_length=20),
        ),
    ]
