# Generated by Django 6.0.6 on 2026-06-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Non payé'), ('partial', 'Partiel'), ('paid', 'Payé')], default='unpaid', max_length=20),
        ),
    ]
