# Generated by Django 6.0.6 on 2026-06-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='apply_vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_rate',
            field=models.IntegerField(default=18),
        ),
    ]
