# Generated by Django 6.0.6 on 2026-07-01 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_apply_vat_sale_delivery_fee_sale_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='apply_vat',
        ),
    ]
