# Generated by Django 6.0.6 on 2026-07-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sale_apply_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='warranty',
            field=models.TextField(blank=True, default='', verbose_name='Garantie'),
        ),
    ]
