# Generated by Django 6.0.6 on 2026-07-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='vat_rate',
            field=models.IntegerField(default=0),
        ),
    ]
