# Generated by Django 6.0.6 on 2026-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='reduction',
            field=models.IntegerField(default=0),
        ),
    ]
