# Generated by Django 6.0.6 on 2026-07-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_quote_status'),
        ('sales', '0008_sale_reduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='quotes.quote'),
        ),
    ]
