# Generated by Django 6.0.6 on 2026-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='labor_cost',
            field=models.IntegerField(default=0, verbose_name="Coût main d'œuvre"),
        ),
    ]
