# Generated by Django 6.0.6 on 2026-08-15 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_sale_company'),
        ('stores', '0004_store_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='stores.store'),
        ),
    ]
