# Generated by Django 6.0.6 on 2026-06-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marque',
            field=models.CharField(max_length=100),
        ),
    ]
