# Generated by Django 6.0.6 on 2026-06-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_stock_product_alter_stock_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
