# Generated by Django 6.0.6 on 2026-06-20 16:18

from django.db import migrations


def forwards(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Marque = apps.get_model('products', 'Marque')

    noms = (
        Product.objects.exclude(marque__isnull=True)
        .exclude(marque__exact='')
        .values_list('marque', flat=True)
        .distinct()
    )

    mapping = {}
    for nom in noms:
        nom_propre = nom.strip()
        if not nom_propre:
            continue
        marque_obj, _ = Marque.objects.get_or_create(
            name__iexact=nom_propre,
            defaults={'name': nom_propre},
        )
        mapping[nom] = marque_obj

    products_to_update = []
    for obj in Product.objects.exclude(marque__isnull=True).exclude(marque__exact=''):
        marque_obj = mapping.get(obj.marque)
        if marque_obj:
            obj.marque_fk_id = marque_obj.id
            products_to_update.append(obj)

    Product.objects.bulk_update(products_to_update, ['marque_fk'], batch_size=500)


def backwards(apps, schema_editor):
    Product = apps.get_model('products', 'Product')

    products_to_update = []
    for obj in Product.objects.exclude(marque_fk__isnull=True):
        obj.marque = obj.marque_fk.name
        products_to_update.append(obj)

    Product.objects.bulk_update(products_to_update, ['marque'], batch_size=500)



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_marque_product_marque_fk'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
