# Generated by Django 6.0.6 on 2026-06-20 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_migrate_marque_to_fk'),
    ]

    operations = [
        migrations.RemoveField(model_name='product', name='marque'),
        migrations.RenameField(model_name='product', old_name='marque_fk', new_name='marque'),
    ]
