# Generated by Django 6.0.6 on 2026-06-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_marque_fk_alter_product_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='marque',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
