# Generated by Django 6.0.6 on 2026-08-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_company_marque_company_product_company'),
        ('subscriptions', '0002_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='marque',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_category_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company', 'slug'), name='unique_category_slug_per_company'),
        ),
        migrations.AddConstraint(
            model_name='marque',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_marque_per_company'),
        ),
    ]
