# Generated by Django 6.0.6 on 2026-08-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_category_slug_alter_marque_name_and_more'),
        ('subscriptions', '0005_remove_subscription_period_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'reference'), name='unique_product_reference_per_company'),
        ),
    ]
